"""Generate dashboard JSON from clean CSV output.

Usage:
    python -m src.dashboard.generate_dashboard_data --input data/clean/chargeback_all.csv --output src/dashboard/dashboard_data.json

This is an alternative to the dashboard_data.json generated by the pipeline.
Use this when you want to regenerate dashboard data from an existing CSV
without re-running the full pipeline.
"""

import argparse
import csv
import json
import sys
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description="Generate dashboard data from clean CSV")
    parser.add_argument("--input", required=True, help="Path to chargeback_all.csv")
    parser.add_argument("--output", required=True, help="Output path for dashboard_data.json")
    args = parser.parse_args()

    records = []
    with open(args.input, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            row["amount_usd"] = float(row.get("amount_usd", 0))
            row["amount_original"] = float(row.get("amount_original", 0))
            records.append(row)

    # Import the dashboard builder from pipeline
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
    from src.etl.pipeline import _build_dashboard_data

    dashboard = _build_dashboard_data(records)

    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(dashboard, f, indent=2)

    print(f"Dashboard data written to {args.output}")
    print(f"Total: ${dashboard['total_usd']:,.2f} USD across {dashboard['total_count']} records")


if __name__ == "__main__":
    main()
